// Template from the launch-video skill: set PROJECT and FRAMES for the new film.
// Writes the four film entry points from one frame list:
//   index.html (16:9, with fork) · index-nofork.html (16:9) · index-square.html (1:1, with fork) · index-square-nofork.html
// Usage: node scripts/build-index.mjs
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";

const PROJECT = { id: "zuse-boxd", name: "Zuse × boxd" };

const FRAMES = [
	{ id: "f01-open", dur: 4 },
	{ id: "f02-machine", dur: 4 },
	{ id: "f03-build-image", dur: 8 },
	{ id: "f04-pick-boxd", dur: 6 },
	{ id: "f05-send", dur: 6 },
	{ id: "f06-url", dur: 4 },
	{ id: "f07-hibernate", dur: 6 },
	{ id: "f08-wake", dur: 2 },
	{ id: "f09-fork", dur: 4, optional: true },
	{ id: "f10-close", dur: 4 },
];

// The master is the project's index.html. The other cuts are tiny sibling projects under
// variants/<name>/ whose compositions/ and assets/ link back to this project, because a
// HyperFrames project may only have one root composition.
const variants = [
	{ name: "master", W: 1920, H: 1080, fork: true },
	{ name: "wide-nofork", W: 1920, H: 1080, fork: false },
	{ name: "square", W: 1440, H: 1440, fork: true },
	{ name: "square-nofork", W: 1440, H: 1440, fork: false },
];

for (const v of variants) {
	const frames = FRAMES.filter((f) => v.fork || !f.optional);
	let t = 0;
	const hosts = frames
		.map((f, i) => {
			const h = `      <div id="${f.id}" data-composition-id="${f.id}" data-composition-src="compositions/frames/${f.id}.html" data-start="${t}" data-duration="${f.dur}" data-track-index="${i + 1}" data-width="${v.W}" data-height="${v.H}"></div>`;
			t += f.dur;
			return h;
		})
		.join("\n");
	const total = t;
	const bed = v.fork ? "bed-fork.wav" : "bed-nofork.wav";
	const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=${v.W}, height=${v.H}" />
    <!-- generated by scripts/build-index.mjs — edit the generator, not this file -->
    <script>window.ZK_FORMAT = { W: ${v.W}, H: ${v.H}, fork: ${v.fork} };</script>
    <script src="assets/vendor/gsap-3.14.2.min.js"></script>
    <script src="compositions/kit/icons.js"></script>
    <script src="compositions/kit/kit.js"></script>
    <link rel="stylesheet" href="compositions/kit/kit.css" />
    <style>
      @font-face { font-family: "Archivo"; font-weight: 100 900; font-stretch: 62% 125%; font-display: block; src: url("assets/fonts/archivo.woff2") format("woff2"); }
      @font-face { font-family: "Geist"; font-weight: 100 900; font-display: block; src: url("assets/fonts/geist.woff2") format("woff2"); }
      @font-face { font-family: "Geist Mono"; font-weight: 100 900; font-display: block; src: url("assets/fonts/geist-mono.woff2") format("woff2"); }
      * { margin: 0; padding: 0; box-sizing: border-box; }
      html, body { margin: 0; width: ${v.W}px; height: ${v.H}px; overflow: hidden; background: #F4F1EB; }
      #root { position: relative; width: 100%; height: 100%; background: #F4F1EB; overflow: hidden; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="${total}" data-width="${v.W}" data-height="${v.H}">
${hosts}
      <audio id="music-bed" src="assets/music/${bed}" data-start="0" data-duration="${total}" data-track-index="20" data-volume="0.8"></audio>
    </div>
    <script>
      const tl = gsap.timeline({ paused: true });
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
`;
	if (v.name === "master") {
		writeFileSync("index.html", html);
	} else {
		const dir = `variants/${v.name}`;
		mkdirSync(dir, { recursive: true });
		writeFileSync(`${dir}/index.html`, html);
		copyFileSync("hyperframes.json", `${dir}/hyperframes.json`);
		for (const link of ["compositions", "assets"]) {
			if (!existsSync(`${dir}/${link}`))
				symlinkSync(`../../${link}`, `${dir}/${link}`);
		}
		writeFileSync(
			`${dir}/meta.json`,
			JSON.stringify(
				{ id: `${PROJECT.id}-${v.name}`, name: `${PROJECT.name} — ${v.name}` },
				null,
				2,
			),
		);
	}
	console.log(`${v.name}: ${v.W}x${v.H}, ${frames.length} frames, ${total}s`);
}
