import {
	LegalPageShell,
	LegalSectionNav,
} from "@/components/legal/legal-page-shell";
import { getSEO } from "@/lib/seo";
import { DISCORD_URL, GITHUB_URL } from "@/lib/site";

export const metadata = getSEO({
	title: "Privacy Policy",
	description:
		"How Zuse handles local project data, accounts, analytics, Cloud Workspaces, and your privacy choices.",
	path: "/privacy",
});

export default function PrivacyPage() {
	return (
		<LegalPageShell>
			<h1 className="mt-8 text-4xl font-semibold">Privacy policy</h1>
			<p className="mt-3 text-sm text-muted-foreground">
				Effective September 9, 2026
			</p>
			<p className="mt-8 text-base leading-7 text-muted-foreground">
				Zuse is built to keep the ordinary coding workspace on your computer.
				This policy explains the data practices for the Zuse website, desktop
				and mobile apps, and optional remote and Cloud Workspace features. It
				also explains where a feature intentionally creates a different data
				path, such as when you sign in, enable notifications, import browser
				cookies, or run an agent in a hosted workspace.
			</p>

			<LegalSectionNav
				label="Privacy policy sections"
				links={[
					{ href: "#data-we-handle", label: "Data we handle" },
					{ href: "#local-first", label: "Local-first" },
					{ href: "#choices", label: "Your choices" },
					{ href: "#contact", label: "Contact" },
				]}
			/>

			<div className="mt-10 space-y-10 text-base leading-7 text-muted-foreground">
				<section>
					<h2 className="text-xl font-medium text-foreground">
						Scope and roles
					</h2>
					<p className="mt-2">
						This policy applies when you visit zuse.sh, use Zuse, join a
						waitlist, contact the project through its official community
						channels, or use an optional account, remote connection, or Cloud
						Workspace. It does not replace the privacy notices of the model,
						source-control, package, deployment, issue-tracking, or other
						services you choose to connect. Those services process data under
						their own terms and policies.
					</p>
					<p className="mt-2">
						For Zuse-operated website, account, analytics, and Cloud Workspace
						features, Zuse determines why and how the described information is
						handled. For a model request, the provider you configure receives
						the request directly or through its own login flow and is
						independently responsible for its handling of that request.
					</p>
				</section>

				<section id="data-we-handle">
					<h2 className="text-xl font-medium text-foreground">
						Data we handle
					</h2>
					<p className="mt-2">
						The information involved depends on the features you use. We may
						handle the following categories:
					</p>
					<ul className="mt-3 list-disc space-y-2 pl-5">
						<li>
							Information you provide, such as an email address submitted to the
							cloud waitlist, feedback or support material you deliberately
							share, and credentials or connection details you choose to
							configure.
						</li>
						<li>
							Account information from the sign-in service, including a verified
							account identifier, email address, and authentication tokens
							needed to maintain your session.
						</li>
						<li>
							Local workspace information generated by your use of the app, such
							as chats, projects, settings, files you choose to open, Git
							activity, terminal activity, browser activity, caches, and locally
							stored diagnostics.
						</li>
						<li>
							Pseudonymous product and reliability analytics from the desktop
							and mobile apps, described in more detail below.
						</li>
						<li>
							For optional remote or Cloud Workspace features, account, device,
							workspace, billing, access-control, and encrypted workspace data
							needed to provide those features.
						</li>
					</ul>
					<p className="mt-2">
						We receive information from you and your device, from the services
						you authorize us to connect, and from service providers that help
						verify an account, operate a cloud workspace, process a
						notification, or measure reliability. The marketing website is not
						part of the desktop and mobile product-analytics system.
					</p>
				</section>

				<section id="local-first">
					<h2 className="text-xl font-medium text-foreground">
						Local work stays local by default
					</h2>
					<p className="mt-2">
						In the ordinary local desktop workflow, chats, project data,
						settings, and related workspace state are stored on your computer.
						Provider API keys are kept in the operating system credential store,
						and model requests go to the provider path you configure. Zuse does
						not upload local project data to a Zuse backend merely to operate
						the local workspace or to power product analytics.
					</p>
					<p className="mt-2">
						That does not make a connected workflow air-gapped. A prompt,
						attached file, command, or tool call can leave your device when you
						send it to a model provider or use an external service. If you
						choose remote access or a Cloud Workspace, the data needed to run
						that feature follows the remote data path described below.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						Accounts and authentication
					</h2>
					<p className="mt-2">
						You can use the core local workspace without creating a Zuse
						account. When you sign in, Zuse uses WorkOS&apos;s public-client
						authorization flow to authenticate you. The app keeps the resulting
						session on your device. Sign-in enables features that need a
						verified account, such as remote access and Cloud Workspaces; it
						does not turn your ordinary local chats into a Zuse-hosted
						transcript.
					</p>
					<p className="mt-2">
						Mobile settings include a Delete account control. It is intended to
						permanently remove the account, linked computers, device
						registrations, and associated cached chats. Reset app is different:
						it removes Zuse data from that phone but does not itself delete a
						remote account or workspace.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						Product and reliability analytics
					</h2>
					<p className="mt-2">
						Desktop and mobile analytics are enabled by default and use a
						pseudonymous installation identity. When you are signed in, Zuse
						uses a one-way, namespaced hash of the account ID rather than
						sending that account ID as the analytics identity. The analytics
						processor may apply standard geographic enrichment to its network
						request.
					</p>
					<p className="mt-2">
						The allowed event catalog covers app activity, screens and stable
						control identifiers, feature use, normalized provider and model
						choices, aggregated token and cost totals, active time, connection
						outcomes, permission and notification decisions, performance, and
						sanitized reliability errors. Active time is measured only while the
						app is in the foreground and you have interacted recently.
					</p>
					<p className="mt-2">
						Analytics are fail-closed: unknown events and properties are
						discarded. Zuse does not send prompts, responses, reasoning, tool
						input or output, commands, source code, file or repository names,
						paths, URLs, branches, titles, account identifiers, names, email
						addresses, credentials, tokens, diagnostic contents, or error stacks
						for product analytics. We do not use autocapture, session replay,
						remote feature flags or remote configuration, or exception/source
						capture in this system.
					</p>
					<p className="mt-2">
						This analytics boundary does not mean every local diagnostic is
						content-free. Diagnostics and crash information kept on your device
						can contain detailed application, system, or error information.
						Review and redact an export before choosing to share it.
					</p>
					<p className="mt-2">
						You can turn collection off immediately in desktop or mobile
						Settings under “Share usage analytics.” Pending desktop analytics
						are deleted when you turn it off. Signing out, resetting the app, or
						deleting an account rotates the analytics identity; already
						collected pseudonymous aggregate history is retained.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						Cloud Workspaces and remote features
					</h2>
					<p className="mt-2">
						Cloud Workspaces are an optional public beta. A cloud workspace runs
						in an isolated hosted environment rather than on your computer. To
						provide it, Zuse handles verified account access, workspace and
						billing metadata, connection tickets, encrypted command envelopes
						and results, and encrypted transcript checkpoints. The hosted
						runtime handles the agent process, repository, files, and terminals.
						Cloud transcript checkpoints are encrypted; they are not a backup of
						the repository filesystem.
					</p>
					<p className="mt-2">
						Cloud credentials are kept encrypted and delivered to the
						authenticated workspace runtime. Zuse&apos;s documented cloud design
						separates the client, API, gateway, runtime, and encrypted storage
						as distinct trust boundaries. A cloud workspace can continue after
						you close the app, so its content is not covered by the local-only
						default while that feature is in use.
					</p>
					<p className="mt-2">
						Remote and paired connections may also make workspace data available
						to the connected device. Mobile clients keep downloaded chats,
						projects, and messages locally for offline use and reconcile them
						with the environment when they reconnect.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						Providers and third parties
					</h2>
					<p className="mt-2">
						Zuse relies on third parties only where a feature requires them.
						These can include WorkOS for account authentication, the analytics
						processor for the limited analytics described above,
						push-notification services for mobile alerts, and cloud
						infrastructure, storage, payment, and compute providers for Cloud
						Workspaces. Model providers, source-control services, browsers,
						package registries, and integrations you choose are separate parties
						that receive information when you direct the app to use them.
					</p>
					<p className="mt-2">
						We may disclose information to service providers acting on our
						behalf, when needed to provide a feature you request, to comply with
						law or a valid legal process, to protect people and the service, or
						as part of a corporate transaction. We do not describe a third party
						as receiving local workspace content unless you use a feature that
						sends it there.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						Device permissions and browser data
					</h2>
					<p className="mt-2">
						Mobile asks for permissions only for the feature that uses them:
						camera access to scan a pairing code or capture an attachment;
						photo-library access to choose or save images; microphone access to
						turn speech into a message; local-network access to connect to a
						local Zuse server; and notification permission for optional
						attention alerts. You can deny or revoke these permissions in your
						device settings. If you enable push notifications while signed in,
						the app registers a device identifier and push token to deliver
						those alerts.
					</p>
					<p className="mt-2">
						The desktop built-in browser uses an isolated in-memory partition.
						If you explicitly import cookies from a local browser profile, Zuse
						copies them into the built-in browser; the imported cookie values
						are encrypted with the app vault for restoration on restart. You can
						clear the encrypted import record and unchanged imported cookies, or
						clear all built-in browser cookies, site storage, and cache from
						desktop settings. A cookie refreshed by a website may require the
						clear-all control. These actions do not change your other browser.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						How we use information and the legal basis for doing so
					</h2>
					<p className="mt-2">
						We use information to run and secure Zuse, authenticate an account,
						provide the features you request, maintain and improve reliability,
						respond to you, and meet legal obligations. Where privacy law
						requires a legal basis, the basis will generally be performance of
						our agreement with you for requested account or cloud features; your
						consent or permission for choices such as device access; legitimate
						interests in security, fraud prevention, and improving the service;
						or compliance with legal obligations. The applicable basis can vary
						by the feature and your location.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						Retention and security
					</h2>
					<p className="mt-2">
						Local data remains on your device until you remove it through the
						app, delete it from the device, or otherwise remove the local
						storage. Some features offer more specific controls, including
						clearing mobile caches, resetting the mobile app, clearing browser
						data, deleting an account, and deleting a cloud workspace. Waitlist
						information is forwarded with a timestamp to the configured signup
						service; we do not state a fixed retention period for it here.
					</p>
					<p className="mt-2">
						For Cloud Workspaces, the current product design treats archive as a
						temporary 30-day retention period. Deleting from the archive skips
						that period and permanently removes the hosted sandbox and encrypted
						transcript objects once deletion completes; a content-free tombstone
						is kept briefly so offline clients can remove their caches.
						Pseudonymous analytics history may remain after an identity is
						rotated, as described above.
					</p>
					<p className="mt-2">
						We use technical and organizational measures designed to protect
						data, including platform-protected secret storage for local
						credentials, encryption for imported browser cookies, and encryption
						and scoped credentials in the cloud design. No system can guarantee
						absolute security; keep your device, operating system, provider
						accounts, and credentials protected as well.
					</p>
				</section>

				<section id="choices">
					<h2 className="text-xl font-medium text-foreground">
						Your choices and privacy rights
					</h2>
					<p className="mt-2">
						You can choose not to create an account, choose which model and
						external providers to use, disable product analytics, decline device
						permissions, turn off notifications, clear browser data, reset a
						mobile device, and delete accounts or cloud workspaces through the
						controls described above. Local project data is also under your
						control through your device and local storage choices.
					</p>
					<p className="mt-2">
						Depending on where you live, you may have rights to request access,
						correction, deletion, restriction, objection, portability, or
						information about our processing of personal data. You may also have
						the right to complain to a privacy regulator. We may need to verify
						a request and may be unable to change data controlled by a
						third-party provider or data that remains only on your own device.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						International processing
					</h2>
					<p className="mt-2">
						Zuse and the providers used for analytics, account, cloud, and other
						optional features may process information in countries other than
						the one where you live. When that happens, the protections and
						transfer mechanisms depend on the feature, provider, and applicable
						law. Your chosen model and integration providers may have their own
						international processing practices.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">Children</h2>
					<p className="mt-2">
						Zuse is a developer tool and is not directed to children. Do not use
						it to submit a child&apos;s personal information. If you believe a
						child has provided personal information through a Zuse-operated
						service, contact us through an official channel below so we can
						review the request.
					</p>
				</section>

				<section>
					<h2 className="text-xl font-medium text-foreground">
						Changes to this policy
					</h2>
					<p className="mt-2">
						We may update this policy as Zuse changes. We will post the updated
						version here and revise the effective date. If a change materially
						affects how we handle personal information, we may provide
						additional notice through the app or another appropriate channel.
					</p>
				</section>

				<section id="contact">
					<h2 className="text-xl font-medium text-foreground">Contact</h2>
					<p className="mt-2">
						For a non-sensitive privacy-policy question, use the official Zuse{" "}
						<a
							href={GITHUB_URL}
							target="_blank"
							rel="noopener noreferrer"
							className="text-primary hover:underline"
						>
							GitHub repository
						</a>{" "}
						or{" "}
						<a
							href={DISCORD_URL}
							target="_blank"
							rel="noopener noreferrer"
							className="text-primary hover:underline"
						>
							Discord community
						</a>
						. Please do not post credentials, private keys, account details, or
						other sensitive workspace content in a public issue or community
						channel. Account deletion is available in the mobile app. Zuse does
						not currently publish a dedicated private privacy-request address,
						so do not use these public channels for an account-specific rights
						request.
					</p>
				</section>
			</div>
		</LegalPageShell>
	);
}
