import { RpcGroup } from "effect/unstable/rpc";
import {
	ProviderAvailabilityRpc,
	ProviderKiroInventoryRpc,
	ProviderOpencodeAddCustomRpc,
	ProviderOpencodeInventoryRpc,
	ProviderOpencodeRemoveAuthRpc,
	ProviderOpencodeRemoveCustomRpc,
	ProviderOpencodeSetAuthRpc,
	ProviderRemoveCredentialRpc,
	ProviderSetCredentialRpc,
	ProviderStartLoginRpc,
	ProviderUpdateRpc,
} from "./agent.ts";
import {
	AnalyticsContextChangesRpc,
	AnalyticsGetContextRpc,
} from "./analytics.ts";
import {
	ApiClientsRpc,
	ApiConnectEnvironmentRpc,
	ApiEnvironmentsRpc,
	ApiRevokeClientRpc,
	EnvironmentConnectRpc,
	EnvironmentsListRpc,
} from "./api.ts";
import { AttachmentReadRpc, AttachmentUploadRpc } from "./attachment.ts";
import {
	AuthGetSessionRpc,
	AuthSessionChangesRpc,
	AuthSignInRpc,
	AuthSignOutRpc,
} from "./auth.ts";
import {
	BrowserCommandsRpc,
	BrowserListCredentialsRpc,
	BrowserRemoveCredentialRpc,
	BrowserRespondRpc,
	BrowserSetCredentialRpc,
} from "./browser.ts";
import {
	CloudAuthConfigureRpc,
	CloudAuthDisconnectRpc,
	CloudAuthLoginCancelRpc,
	CloudAuthLoginPollRpc,
	CloudAuthLoginStartRpc,
	CloudAuthProvisionRpc,
	CloudAuthStatusRpc,
} from "./cloud-auth.ts";
import {
	CloudBillingSetCapRpc,
	CloudBillingSummaryRpc,
	CloudBillingUsageRpc,
} from "./cloud-billing.ts";
import {
	CloudGithubDisconnectRpc,
	CloudGithubInstallRpc,
	CloudGithubStatusRpc,
} from "./cloud-github.ts";
import {
	CloudAccountImageBuildRpc,
	CloudAccountImageStatusRpc,
	CloudChatsListRpc,
	CloudCommandsCancelRpc,
	CloudCommandsEnqueueRpc,
	CloudCommandsStatusRpc,
	CloudCommandsWatchRpc,
	CloudProjectsConnectRpc,
	CloudProjectsListRpc,
	CloudProjectsPrepareRpc,
	CloudProjectsRemoveRpc,
	CloudProvidersRpc,
	CloudTranscriptCheckpointGetRpc,
	CloudTranscriptMessagePageGetRpc,
	CloudWorkspaceDataKeyRpc,
	CloudWorkspacesArchiveRpc,
	CloudWorkspacesConnectRpc,
	CloudWorkspacesCreateRpc,
	CloudWorkspacesDeleteRpc,
	CloudWorkspacesGetRpc,
	CloudWorkspacesListRpc,
	CloudWorkspacesPauseRpc,
	CloudWorkspacesPreviewUrlRpc,
	CloudWorkspacesRestartRpc,
	CloudWorkspacesResumeRpc,
	CloudWorkspacesSshAccessRpc,
	CloudWorkspacesUnarchiveRpc,
	CloudWorkspacesWatchRpc,
} from "./cloud-workspaces.ts";
import {
	ApiLinkRpc,
	ApiStatusRpc,
	ApiUnlinkRpc,
	ConnectApiConfigRpc,
	ConnectDescribeRpc,
	ConnectLinkProofRpc,
} from "./connect.ts";
import { ContextSaveTextRpc } from "./context.ts";
import {
	DiagnosticsCaptureRpc,
	DiagnosticsEventsRpc,
	DiagnosticsExportRpc,
	DiagnosticsIngestRpc,
	DiagnosticsOverviewRpc,
	DiagnosticsProcessesRpc,
	DiagnosticsSignalRpc,
} from "./diagnostics.ts";
import {
	ExternalThreadsContinueRpc,
	ExternalThreadsListRpc,
} from "./external-thread.ts";
import {
	FsCreateDirectoryRpc,
	FsCreateFileRpc,
	FsListPathsRpc,
	FsMoveRpc,
	FsReadExternalFileRpc,
	FsReadFileRpc,
	FsRemoveRpc,
	FsTreeRpc,
	FsWatchTreeRpc,
	FsWriteExternalFileRpc,
	FsWriteFileRpc,
} from "./fs.ts";
import {
	GitBranchesRpc,
	GitChangesRpc,
	GitCommitRpc,
	GitCreateReviewCommentRpc,
	GitDiffRpc,
	GitFixFailingChecksRpc,
	GitInitRpc,
	GitIssueMarkdownRpc,
	GitListIssuesRpc,
	GitListPrsRpc,
	GitLogRpc,
	GitMarkReadyRpc,
	GitMergePrRpc,
	GitOriginRpc,
	GitPrDetailsRpc,
	GitPrNotificationClaimRpc,
	GitPrStateRpc,
	GitPullRpc,
	GitPushRpc,
	GitResetRemoteApplyRpc,
	GitResetRemotePreviewRpc,
	GitResolveConflictRpc,
	GitRestoreFileToBaseRpc,
	GitRevertAllRpc,
	GitRevertFileRpc,
	GitReviewFileContentsRpc,
	GitReviewIdentityRpc,
	GitReviewPatchesRpc,
	GitReviewSummaryRpc,
	GitStashPopRpc,
	GitStashRpc,
	GitStatusRpc,
	GitSwitchBranchRpc,
	GitUserNameRpc,
	GitWorkspaceChangesRpc,
	GitWorkspaceSnapshotRpc,
} from "./git.ts";
import { ConnectHandshakeRpc } from "./handshake.ts";
import { HostOpenSessionRpc } from "./host.ts";
import {
	KeybindingsGetRpc,
	KeybindingsReplaceRpc,
	KeybindingsStreamRpc,
} from "./keybindings.ts";
import {
	LinearConnectRpc,
	LinearDisconnectRpc,
	LinearListConnectionsRpc,
	LinearListIssuesRpc,
	LinearPrepareContextRpc,
} from "./linear.ts";
import {
	AccountAccessConfigureCustomRpc,
	AccountAccessDisconnectRpc,
	AccountAccessSetCredentialRpc,
	AccountAccessStartLoginRpc,
	AccountAccessStatusRpc,
	MachinePrivateNetworkEnableRpc,
	MachinePrivateNetworkStatusRpc,
	MachineResourcesWatchRpc,
	MachineRuntimeStatusRpc,
	MachineRuntimeTargetRpc,
	MachineRuntimeUpdateRpc,
	MachineSshKeysAddRpc,
	MachineSshKeysListRpc,
	MachineSshKeysRemoveRpc,
	MachineSshModeSetRpc,
	MachinesBillingPortalRpc,
	MachinesCancelRpc,
	MachinesCheckoutRpc,
	MachinesCreateRpc,
	MachinesDestroyRpc,
	MachinesEntitlementsRpc,
	MachinesGetRpc,
	MachinesListRpc,
	MachinesOffersRpc,
	MachinesRecoverRpc,
} from "./machines.ts";
import {
	McpAuthenticateRpc,
	McpListRpc,
	McpRefreshRpc,
	McpSetEnabledRpc,
} from "./mcp.ts";
import {
	PairingListNearbyRequestsRpc,
	PairingListTokensRpc,
	PairingResolveNearbyRequestRpc,
	PairingRevokeTokenRpc,
	PairingStartRpc,
} from "./pairing.ts";
import {
	PermissionDecideRpc,
	PermissionListDecisionsRpc,
	PermissionListPendingRpc,
	PermissionRequestsRpc,
	PermissionRevokeDecisionRpc,
} from "./permission.ts";
import { PingRpc } from "./ping.ts";
import { PokemonEnsureSpriteCachedRpc, PokemonPokedexRpc } from "./pokemon.ts";
import { PreviewsListServersRpc } from "./previews.ts";
import {
	PtyCloseRpc,
	PtyListRpc,
	PtyOpenRpc,
	PtyOutputRpc,
	PtyResizeRpc,
	PtyWriteRpc,
} from "./pty.ts";
import {
	RepositorySettingsGetRpc,
	RepositorySettingsUpdateRpc,
} from "./repository-settings.ts";
import {
	ChatArchiveJobsRpc,
	ChatArchivePreviewRpc,
	ChatArchiveRpc,
	ChatArchiveStatusRpc,
	ChatCreateRpc,
	ChatCreationDiscardRpc,
	ChatCreationListRpc,
	ChatCreationRecoverRpc,
	ChatCreationStreamRpc,
	ChatDeleteRpc,
	ChatDirectoryStatusRpc,
	ChatGetRpc,
	ChatListRpc,
	ChatMarkReadRpc,
	ChatRenameRpc,
	ChatSetActiveSessionRpc,
	ChatSetWorktreeRpc,
	ChatStreamChangesRpc,
	ChatUnarchiveRpc,
	MessagesInterruptRpc,
	MessagesListRpc,
	MessagesQueueAddRpc,
	MessagesQueueDeleteRpc,
	MessagesQueueFlushRpc,
	MessagesQueueListRpc,
	MessagesQueueReorderRpc,
	MessagesQueueResumeRpc,
	MessagesQueueRunNextRpc,
	MessagesQueueUpdateRpc,
	MessagesSendRpc,
	SessionAnswerQuestionRpc,
	SessionArchiveRpc,
	SessionCreateRpc,
	SessionDeleteRpc,
	SessionEventsHeadRpc,
	SessionEventsRpc,
	SessionExportTranscriptRpc,
	SessionForkRpc,
	SessionGetRpc,
	SessionGoalClearRpc,
	SessionGoalGetRpc,
	SessionGoalSetRpc,
	SessionGoalStreamRpc,
	SessionLatestPlanRpc,
	SessionListRpc,
	SessionMcpUpdateRpc,
	SessionMessagesPageRpc,
	SessionPlanRespondRpc,
	SessionRenameRpc,
	SessionResumeRpc,
	SessionSetModelRpc,
	SessionSetPermissionModeRpc,
	SessionSetProviderRpc,
	SessionSetRuntimeModeRpc,
	SessionSetWorktreeRpc,
	SessionStreamChangesRpc,
	SessionUnarchiveRpc,
} from "./session.ts";
import {
	SettingsGetRpc,
	SettingsMigrateLocalStorageRpc,
	SettingsStreamRpc,
	SettingsUpdateRpc,
} from "./settings.ts";
import {
	SkillListForProjectRpc,
	SkillListRpc,
	SkillStreamRpc,
} from "./skill.ts";
import { UsageOverviewRpc, UsageReportRpc, UsageSessionsRpc } from "./usage.ts";
import { UsageLimitsHistoryRpc, UsageLimitsRpc } from "./usage-limits.ts";
import {
	VoiceCapabilitiesRpc,
	VoicePrewarmRpc,
	VoiceResolveAuthRpc,
	VoiceTranscribeRpc,
} from "./voice.ts";
import {
	WorkspaceAddRpc,
	WorkspaceBrowseDirectoryRpc,
	WorkspaceCloneRepoRpc,
	WorkspaceCreateProjectRpc,
	WorkspaceGetSelectedRpc,
	WorkspaceGhAuthStatusRpc,
	WorkspaceListGithubReposRpc,
	WorkspaceListRpc,
	WorkspacePickFolderRpc,
	WorkspaceRemoveRpc,
	WorkspaceSearchFilesRpc,
	WorkspaceSetSelectedRpc,
	WorkspaceStreamChangesRpc,
} from "./workspace.ts";
import {
	WorktreeCreateRpc,
	WorktreeGetRpc,
	WorktreeListRpc,
	WorktreeRemoveRpc,
	WorktreeRenameBranchRpc,
	WorktreeRerunSetupRpc,
	WorktreeSetupStreamRpc,
	WorktreeStartRunRpc,
} from "./worktree.ts";

/**
 * The single source of truth for every RPC method exposed by the main process.
 * Both server (apps/desktop) and client (apps/renderer) build against this.
 *
 * Add new RPCs by importing them here and including them in the group.
 */
export const MemoizeRpcs = RpcGroup.make(
	PingRpc,
	PreviewsListServersRpc,
	AnalyticsGetContextRpc,
	AnalyticsContextChangesRpc,
	AuthGetSessionRpc,
	AuthSignInRpc,
	AuthSignOutRpc,
	AuthSessionChangesRpc,
	LinearListConnectionsRpc,
	LinearConnectRpc,
	LinearDisconnectRpc,
	LinearListIssuesRpc,
	LinearPrepareContextRpc,
	PairingStartRpc,
	PairingListTokensRpc,
	PairingRevokeTokenRpc,
	PairingListNearbyRequestsRpc,
	PairingResolveNearbyRequestRpc,
	ConnectHandshakeRpc,
	ConnectDescribeRpc,
	ConnectLinkProofRpc,
	ConnectApiConfigRpc,
	ApiLinkRpc,
	ApiStatusRpc,
	ApiUnlinkRpc,
	EnvironmentsListRpc,
	EnvironmentConnectRpc,
	CloudBillingSummaryRpc,
	CloudBillingUsageRpc,
	CloudBillingSetCapRpc,
	CloudAuthStatusRpc,
	CloudAuthProvisionRpc,
	CloudAuthConfigureRpc,
	CloudAuthLoginStartRpc,
	CloudAuthLoginPollRpc,
	CloudAuthLoginCancelRpc,
	CloudAuthDisconnectRpc,
	CloudGithubStatusRpc,
	CloudGithubInstallRpc,
	CloudGithubDisconnectRpc,
	CloudAccountImageStatusRpc,
	CloudAccountImageBuildRpc,
	CloudProvidersRpc,
	CloudProjectsListRpc,
	CloudProjectsConnectRpc,
	CloudProjectsRemoveRpc,
	CloudProjectsPrepareRpc,
	CloudWorkspacesListRpc,
	CloudWorkspacesGetRpc,
	CloudWorkspacesWatchRpc,
	CloudWorkspacesCreateRpc,
	CloudWorkspacesConnectRpc,
	CloudChatsListRpc,
	CloudWorkspacesPauseRpc,
	CloudWorkspacesResumeRpc,
	CloudWorkspacesRestartRpc,
	CloudWorkspacesSshAccessRpc,
	CloudWorkspacesPreviewUrlRpc,
	CloudWorkspacesArchiveRpc,
	CloudWorkspacesUnarchiveRpc,
	CloudWorkspacesDeleteRpc,
	CloudCommandsEnqueueRpc,
	CloudCommandsStatusRpc,
	CloudCommandsWatchRpc,
	CloudCommandsCancelRpc,
	CloudWorkspaceDataKeyRpc,
	CloudTranscriptCheckpointGetRpc,
	CloudTranscriptMessagePageGetRpc,
	MachinesOffersRpc,
	MachinesListRpc,
	MachinesGetRpc,
	MachinesCreateRpc,
	MachinesCancelRpc,
	MachinesRecoverRpc,
	MachinesDestroyRpc,
	MachinesCheckoutRpc,
	MachinesBillingPortalRpc,
	MachinesEntitlementsRpc,
	MachineSshKeysAddRpc,
	MachineSshKeysListRpc,
	MachineSshKeysRemoveRpc,
	MachinePrivateNetworkEnableRpc,
	MachinePrivateNetworkStatusRpc,
	MachineRuntimeTargetRpc,
	MachineRuntimeStatusRpc,
	MachineRuntimeUpdateRpc,
	MachineResourcesWatchRpc,
	MachineSshModeSetRpc,
	AccountAccessStatusRpc,
	AccountAccessStartLoginRpc,
	AccountAccessSetCredentialRpc,
	AccountAccessConfigureCustomRpc,
	AccountAccessDisconnectRpc,
	ApiEnvironmentsRpc,
	ApiConnectEnvironmentRpc,
	ApiClientsRpc,
	ApiRevokeClientRpc,
	WorkspaceAddRpc,
	WorkspaceBrowseDirectoryRpc,
	WorkspaceListRpc,
	WorkspaceRemoveRpc,
	WorkspacePickFolderRpc,
	WorkspaceGetSelectedRpc,
	WorkspaceSetSelectedRpc,
	WorkspaceStreamChangesRpc,
	WorkspaceSearchFilesRpc,
	WorkspaceCloneRepoRpc,
	WorkspaceCreateProjectRpc,
	WorkspaceListGithubReposRpc,
	WorkspaceGhAuthStatusRpc,
	ExternalThreadsListRpc,
	ExternalThreadsContinueRpc,
	PtyOpenRpc,
	PtyListRpc,
	PtyWriteRpc,
	PtyResizeRpc,
	PtyCloseRpc,
	PtyOutputRpc,
	GitLogRpc,
	GitStatusRpc,
	GitBranchesRpc,
	GitSwitchBranchRpc,
	GitUserNameRpc,
	GitWorkspaceChangesRpc,
	GitWorkspaceSnapshotRpc,
	GitOriginRpc,
	GitPrStateRpc,
	GitPrNotificationClaimRpc,
	GitPrDetailsRpc,
	GitListPrsRpc,
	GitListIssuesRpc,
	GitIssueMarkdownRpc,
	GitChangesRpc,
	GitReviewSummaryRpc,
	GitReviewPatchesRpc,
	GitReviewFileContentsRpc,
	GitReviewIdentityRpc,
	GitDiffRpc,
	GitCommitRpc,
	GitCreateReviewCommentRpc,
	GitPushRpc,
	GitPullRpc,
	GitStashRpc,
	GitStashPopRpc,
	GitResetRemotePreviewRpc,
	GitResetRemoteApplyRpc,
	GitResolveConflictRpc,
	GitMergePrRpc,
	GitMarkReadyRpc,
	GitInitRpc,
	GitFixFailingChecksRpc,
	GitRevertFileRpc,
	GitRestoreFileToBaseRpc,
	GitRevertAllRpc,
	FsTreeRpc,
	FsWatchTreeRpc,
	FsListPathsRpc,
	FsMoveRpc,
	FsReadFileRpc,
	FsWriteFileRpc,
	FsCreateFileRpc,
	FsCreateDirectoryRpc,
	FsRemoveRpc,
	FsReadExternalFileRpc,
	FsWriteExternalFileRpc,
	ProviderAvailabilityRpc,
	ProviderRemoveCredentialRpc,
	ProviderSetCredentialRpc,
	ProviderOpencodeInventoryRpc,
	ProviderKiroInventoryRpc,
	ProviderOpencodeSetAuthRpc,
	ProviderOpencodeRemoveAuthRpc,
	ProviderOpencodeAddCustomRpc,
	ProviderOpencodeRemoveCustomRpc,
	ProviderStartLoginRpc,
	ProviderUpdateRpc,
	ChatArchivePreviewRpc,
	McpListRpc,
	McpRefreshRpc,
	McpSetEnabledRpc,
	McpAuthenticateRpc,
	ChatListRpc,
	ChatGetRpc,
	ChatCreateRpc,
	ChatCreationListRpc,
	ChatCreationStreamRpc,
	ChatCreationDiscardRpc,
	ChatCreationRecoverRpc,
	ChatRenameRpc,
	ChatMarkReadRpc,
	ChatStreamChangesRpc,
	ChatSetWorktreeRpc,
	ChatSetActiveSessionRpc,
	ChatArchiveRpc,
	ChatArchiveStatusRpc,
	ChatArchiveJobsRpc,
	ChatDirectoryStatusRpc,
	ChatUnarchiveRpc,
	ChatDeleteRpc,
	SessionListRpc,
	SessionStreamChangesRpc,
	SessionMcpUpdateRpc,
	SessionGetRpc,
	SessionCreateRpc,
	SessionRenameRpc,
	SessionGoalGetRpc,
	SessionGoalSetRpc,
	SessionGoalClearRpc,
	SessionGoalStreamRpc,
	SessionSetModelRpc,
	SessionSetProviderRpc,
	SessionArchiveRpc,
	SessionUnarchiveRpc,
	SessionDeleteRpc,
	SessionEventsHeadRpc,
	SessionEventsRpc,
	SessionMessagesPageRpc,
	SessionForkRpc,
	SessionExportTranscriptRpc,
	SessionLatestPlanRpc,
	SessionResumeRpc,
	SessionSetRuntimeModeRpc,
	SessionSetPermissionModeRpc,
	SessionAnswerQuestionRpc,
	SessionPlanRespondRpc,
	SessionSetWorktreeRpc,
	MessagesListRpc,
	MessagesSendRpc,
	MessagesInterruptRpc,
	MessagesQueueListRpc,
	MessagesQueueAddRpc,
	MessagesQueueUpdateRpc,
	MessagesQueueDeleteRpc,
	MessagesQueueRunNextRpc,
	MessagesQueueReorderRpc,
	MessagesQueueFlushRpc,
	MessagesQueueResumeRpc,
	AttachmentUploadRpc,
	AttachmentReadRpc,
	ContextSaveTextRpc,
	SkillListRpc,
	SkillListForProjectRpc,
	SkillStreamRpc,
	PermissionRequestsRpc,
	PermissionDecideRpc,
	PermissionListPendingRpc,
	PermissionListDecisionsRpc,
	PermissionRevokeDecisionRpc,
	PokemonPokedexRpc,
	PokemonEnsureSpriteCachedRpc,
	BrowserCommandsRpc,
	BrowserRespondRpc,
	BrowserSetCredentialRpc,
	BrowserListCredentialsRpc,
	BrowserRemoveCredentialRpc,
	WorktreeCreateRpc,
	WorktreeListRpc,
	WorktreeGetRpc,
	WorktreeRenameBranchRpc,
	WorktreeRerunSetupRpc,
	WorktreeSetupStreamRpc,
	WorktreeStartRunRpc,
	WorktreeRemoveRpc,
	RepositorySettingsGetRpc,
	RepositorySettingsUpdateRpc,
	SettingsGetRpc,
	SettingsUpdateRpc,
	SettingsStreamRpc,
	SettingsMigrateLocalStorageRpc,
	UsageReportRpc,
	UsageOverviewRpc,
	UsageSessionsRpc,
	UsageLimitsRpc,
	UsageLimitsHistoryRpc,
	VoiceCapabilitiesRpc,
	VoicePrewarmRpc,
	VoiceTranscribeRpc,
	VoiceResolveAuthRpc,
	HostOpenSessionRpc,
	DiagnosticsExportRpc,
	DiagnosticsOverviewRpc,
	DiagnosticsEventsRpc,
	DiagnosticsProcessesRpc,
	DiagnosticsSignalRpc,
	DiagnosticsIngestRpc,
	DiagnosticsCaptureRpc,
	KeybindingsGetRpc,
	KeybindingsReplaceRpc,
	KeybindingsStreamRpc,
	SessionSetWorktreeRpc,
);
export type MemoizeRpcs = typeof MemoizeRpcs;

/**
 * The Electron IPC channel name used to transport RPC frames in both
 * directions. The frame body is the bytes/string emitted by the configured
 * `RpcSerialization` (we use NDJSON in v1 — see `apps/desktop/src/runtime.ts`).
 *
 * Renderer → main: `ipcRenderer.send(IPC_CHANNEL, frame)`
 * Main → renderer: `webContents.send(IPC_CHANNEL, frame)`
 */
export const IPC_CHANNEL = "zuse:rpc" as const;
