import { RpcGroup } from "effect/unstable/rpc";

import {
	ProviderAvailabilityRpc,
	ProviderOpencodeAddCustomRpc,
	ProviderOpencodeInventoryRpc,
	ProviderOpencodeRemoveAuthRpc,
	ProviderOpencodeRemoveCustomRpc,
	ProviderOpencodeSetAuthRpc,
	ProviderSetCredentialRpc,
	ProviderStartLoginRpc,
	ProviderUpdateRpc,
} from "./agent.ts";
import { AttachmentUploadRpc } from "./attachment.ts";
import {
	AuthGetSessionRpc,
	AuthSessionChangesRpc,
	AuthSignInRpc,
	AuthSignOutRpc,
} from "./auth.ts";
import {
	BrowserCommandsRpc,
	BrowserFillForOriginRpc,
	BrowserListCredentialsRpc,
	BrowserRemoveCredentialRpc,
	BrowserRespondRpc,
	BrowserSetCredentialRpc,
} from "./browser.ts";
import {
	ConnectDescribeRpc,
	ConnectLinkProofRpc,
	ConnectRelayConfigRpc,
	RelayLinkRpc,
	RelayStatusRpc,
	RelayUnlinkRpc,
} from "./connect.ts";
import { ContextSaveTextRpc } from "./context.ts";
import { DiagnosticsExportRpc } from "./diagnostics.ts";
import {
	ExternalThreadsContinueRpc,
	ExternalThreadsListRpc,
} from "./external-thread.ts";
import {
	FsCreateDirectoryRpc,
	FsCreateFileRpc,
	FsReadExternalFileRpc,
	FsReadFileRpc,
	FsRemoveRpc,
	FsTreeRpc,
	FsWatchTreeRpc,
	FsWriteExternalFileRpc,
	FsWriteFileRpc,
} from "./fs.ts";
import {
	GitBranchesRpc,
	GitChangesRpc,
	GitCommitRpc,
	GitDiffRpc,
	GitDiffStatRpc,
	GitFixFailingChecksRpc,
	GitHeadChangedRpc,
	GitInitRpc,
	GitIssueMarkdownRpc,
	GitListIssuesRpc,
	GitListPrsRpc,
	GitLogRpc,
	GitMarkReadyRpc,
	GitMergePrRpc,
	GitOriginRpc,
	GitPrDetailsRpc,
	GitPrStateRpc,
	GitPushRpc,
	GitRenameBranchRpc,
	GitRevertAllRpc,
	GitRevertFileRpc,
	GitStatusRpc,
	GitSwitchBranchRpc,
	GitUserNameRpc,
} from "./git.ts";
import { ConnectHandshakeRpc } from "./handshake.ts";
import {
	KeybindingsGetRpc,
	KeybindingsReplaceRpc,
	KeybindingsStreamRpc,
} from "./keybindings.ts";
import {
	LinearConnectRpc,
	LinearDisconnectRpc,
	LinearListConnectionsRpc,
	LinearListIssuesRpc,
	LinearPrepareContextRpc,
} from "./linear.ts";
import {
	PairingListTokensRpc,
	PairingRevokeTokenRpc,
	PairingStartRpc,
} from "./pairing.ts";
import {
	PermissionDecideRpc,
	PermissionListDecisionsRpc,
	PermissionListPendingRpc,
	PermissionRequestsRpc,
	PermissionRevokeDecisionRpc,
} from "./permission.ts";
import { PingRpc } from "./ping.ts";
import { PokemonEnsureSpriteCachedRpc, PokemonPokedexRpc } from "./pokemon.ts";
import {
	PtyCloseRpc,
	PtyOpenRpc,
	PtyOutputRpc,
	PtyResizeRpc,
	PtyWriteRpc,
} from "./pty.ts";
import {
	RepositorySettingsGetRpc,
	RepositorySettingsUpdateRpc,
} from "./repository-settings.ts";
import {
	ChatArchivePreviewRpc,
	ChatArchiveRpc,
	ChatCreateRpc,
	ChatDeleteRpc,
	ChatGetRpc,
	ChatListRpc,
	ChatMarkReadRpc,
	ChatRenameRpc,
	ChatSetActiveSessionRpc,
	ChatSetWorktreeRpc,
	ChatStreamChangesRpc,
	ChatUnarchiveRpc,
	MessagesInterruptRpc,
	MessagesListRpc,
	MessagesQueueAddRpc,
	MessagesQueueDeleteRpc,
	MessagesQueueFlushRpc,
	MessagesQueueListRpc,
	MessagesQueueReorderRpc,
	MessagesQueueResumeRpc,
	MessagesQueueSendNowRpc,
	MessagesQueueStreamRpc,
	MessagesQueueUpdateRpc,
	MessagesSendRpc,
	SessionAnswerQuestionRpc,
	SessionArchiveRpc,
	SessionCreateRpc,
	SessionDeleteRpc,
	SessionEventsRpc,
	SessionExportTranscriptRpc,
	SessionForkRpc,
	SessionGetRpc,
	SessionGoalClearRpc,
	SessionGoalGetRpc,
	SessionGoalSetRpc,
	SessionGoalStreamRpc,
	SessionLatestPlanRpc,
	SessionListRpc,
	SessionMcpUpdateRpc,
	SessionPlanRespondRpc,
	SessionRenameRpc,
	SessionResumeRpc,
	SessionSetModelRpc,
	SessionSetPermissionModeRpc,
	SessionSetProviderRpc,
	SessionSetRuntimeModeRpc,
	SessionSetWorktreeRpc,
	SessionStreamChangesRpc,
	SessionUnarchiveRpc,
} from "./session.ts";
import {
	SettingsGetRpc,
	SettingsMigrateLocalStorageRpc,
	SettingsStreamRpc,
	SettingsUpdateRpc,
} from "./settings.ts";
import {
	SkillListForProjectRpc,
	SkillListRpc,
	SkillStreamRpc,
} from "./skill.ts";
import { UsageOverviewRpc, UsageReportRpc, UsageSessionsRpc } from "./usage.ts";
import { UsageLimitsHistoryRpc, UsageLimitsRpc } from "./usage-limits.ts";
import {
	WorkspaceAddRpc,
	WorkspaceCloneRepoRpc,
	WorkspaceCreateProjectRpc,
	WorkspaceGetSelectedRpc,
	WorkspaceGhAuthStatusRpc,
	WorkspaceListGithubReposRpc,
	WorkspaceListRpc,
	WorkspacePickFolderRpc,
	WorkspaceRemoveRpc,
	WorkspaceSearchFilesRpc,
	WorkspaceSetSelectedRpc,
} from "./workspace.ts";
import {
	WorktreeCreateRpc,
	WorktreeGetRpc,
	WorktreeListRpc,
	WorktreeRemoveRpc,
	WorktreeRerunSetupRpc,
	WorktreeSetupStreamRpc,
	WorktreeStartRunRpc,
} from "./worktree.ts";

/**
 * The single source of truth for every RPC method exposed by the main process.
 * Both server (apps/desktop) and client (apps/renderer) build against this.
 *
 * Add new RPCs by importing them here and including them in the group.
 */
export const MemoizeRpcs = RpcGroup.make(
	PingRpc,
	AuthGetSessionRpc,
	AuthSignInRpc,
	AuthSignOutRpc,
	AuthSessionChangesRpc,
	LinearListConnectionsRpc,
	LinearConnectRpc,
	LinearDisconnectRpc,
	LinearListIssuesRpc,
	LinearPrepareContextRpc,
	PairingStartRpc,
	PairingListTokensRpc,
	PairingRevokeTokenRpc,
	ConnectHandshakeRpc,
	ConnectDescribeRpc,
	ConnectLinkProofRpc,
	ConnectRelayConfigRpc,
	RelayLinkRpc,
	RelayStatusRpc,
	RelayUnlinkRpc,
	WorkspaceAddRpc,
	WorkspaceListRpc,
	WorkspaceRemoveRpc,
	WorkspacePickFolderRpc,
	WorkspaceGetSelectedRpc,
	WorkspaceSetSelectedRpc,
	WorkspaceSearchFilesRpc,
	WorkspaceCloneRepoRpc,
	WorkspaceCreateProjectRpc,
	WorkspaceListGithubReposRpc,
	WorkspaceGhAuthStatusRpc,
	ExternalThreadsListRpc,
	ExternalThreadsContinueRpc,
	PtyOpenRpc,
	PtyWriteRpc,
	PtyResizeRpc,
	PtyCloseRpc,
	PtyOutputRpc,
	GitLogRpc,
	GitStatusRpc,
	GitBranchesRpc,
	GitSwitchBranchRpc,
	GitRenameBranchRpc,
	GitUserNameRpc,
	GitHeadChangedRpc,
	GitOriginRpc,
	GitPrStateRpc,
	GitPrDetailsRpc,
	GitListPrsRpc,
	GitListIssuesRpc,
	GitIssueMarkdownRpc,
	GitChangesRpc,
	GitDiffRpc,
	GitCommitRpc,
	GitPushRpc,
	GitMergePrRpc,
	GitMarkReadyRpc,
	GitInitRpc,
	GitFixFailingChecksRpc,
	GitRevertFileRpc,
	GitRevertAllRpc,
	GitDiffStatRpc,
	FsTreeRpc,
	FsWatchTreeRpc,
	FsReadFileRpc,
	FsWriteFileRpc,
	FsCreateFileRpc,
	FsCreateDirectoryRpc,
	FsRemoveRpc,
	FsReadExternalFileRpc,
	FsWriteExternalFileRpc,
	ProviderAvailabilityRpc,
	ProviderSetCredentialRpc,
	ProviderOpencodeInventoryRpc,
	ProviderOpencodeSetAuthRpc,
	ProviderOpencodeRemoveAuthRpc,
	ProviderOpencodeAddCustomRpc,
	ProviderOpencodeRemoveCustomRpc,
	ProviderStartLoginRpc,
	ProviderUpdateRpc,
	ChatArchivePreviewRpc,
	ChatListRpc,
	ChatGetRpc,
	ChatCreateRpc,
	ChatRenameRpc,
	ChatMarkReadRpc,
	ChatStreamChangesRpc,
	ChatSetWorktreeRpc,
	ChatSetActiveSessionRpc,
	ChatArchiveRpc,
	ChatUnarchiveRpc,
	ChatDeleteRpc,
	SessionListRpc,
	SessionStreamChangesRpc,
	SessionMcpUpdateRpc,
	SessionGetRpc,
	SessionCreateRpc,
	SessionRenameRpc,
	SessionGoalGetRpc,
	SessionGoalSetRpc,
	SessionGoalClearRpc,
	SessionGoalStreamRpc,
	SessionSetModelRpc,
	SessionSetProviderRpc,
	SessionArchiveRpc,
	SessionUnarchiveRpc,
	SessionDeleteRpc,
	SessionEventsRpc,
	SessionForkRpc,
	SessionExportTranscriptRpc,
	SessionLatestPlanRpc,
	SessionResumeRpc,
	SessionSetRuntimeModeRpc,
	SessionSetPermissionModeRpc,
	SessionAnswerQuestionRpc,
	SessionPlanRespondRpc,
	SessionSetWorktreeRpc,
	MessagesListRpc,
	MessagesSendRpc,
	MessagesInterruptRpc,
	MessagesQueueListRpc,
	MessagesQueueStreamRpc,
	MessagesQueueAddRpc,
	MessagesQueueUpdateRpc,
	MessagesQueueDeleteRpc,
	MessagesQueueSendNowRpc,
	MessagesQueueReorderRpc,
	MessagesQueueFlushRpc,
	MessagesQueueResumeRpc,
	AttachmentUploadRpc,
	ContextSaveTextRpc,
	SkillListRpc,
	SkillListForProjectRpc,
	SkillStreamRpc,
	PermissionRequestsRpc,
	PermissionDecideRpc,
	PermissionListPendingRpc,
	PermissionListDecisionsRpc,
	PermissionRevokeDecisionRpc,
	PokemonPokedexRpc,
	PokemonEnsureSpriteCachedRpc,
	BrowserCommandsRpc,
	BrowserRespondRpc,
	BrowserSetCredentialRpc,
	BrowserListCredentialsRpc,
	BrowserRemoveCredentialRpc,
	BrowserFillForOriginRpc,
	WorktreeCreateRpc,
	WorktreeListRpc,
	WorktreeGetRpc,
	WorktreeRerunSetupRpc,
	WorktreeSetupStreamRpc,
	WorktreeStartRunRpc,
	WorktreeRemoveRpc,
	RepositorySettingsGetRpc,
	RepositorySettingsUpdateRpc,
	SettingsGetRpc,
	SettingsUpdateRpc,
	SettingsStreamRpc,
	SettingsMigrateLocalStorageRpc,
	UsageReportRpc,
	UsageOverviewRpc,
	UsageSessionsRpc,
	UsageLimitsRpc,
	UsageLimitsHistoryRpc,
	DiagnosticsExportRpc,
	KeybindingsGetRpc,
	KeybindingsReplaceRpc,
	KeybindingsStreamRpc,
	SessionSetWorktreeRpc,
);
export type MemoizeRpcs = typeof MemoizeRpcs;

/**
 * The Electron IPC channel name used to transport RPC frames in both
 * directions. The frame body is the bytes/string emitted by the configured
 * `RpcSerialization` (we use NDJSON in v1 — see `apps/desktop/src/runtime.ts`).
 *
 * Renderer → main: `ipcRenderer.send(IPC_CHANNEL, frame)`
 * Main → renderer: `webContents.send(IPC_CHANNEL, frame)`
 */
export const IPC_CHANNEL = "zuse:rpc" as const;
