import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "../packages/i18n/src");
const namespaces = readdirSync(`${root}/catalogs/en`)
	.filter((f) => f.endsWith(".json"))
	.map((f) => f.slice(0, -5))
	.sort();
const locales = Object.keys(
	JSON.parse(readFileSync(`${root}/locales.json`, "utf8")),
);
const accents = {
	a: "à",
	e: "ë",
	i: "ï",
	o: "ô",
	u: "ü",
	A: "À",
	E: "Ë",
	I: "Ï",
	O: "Ô",
	U: "Ü",
};
export const pseudo = (text) =>
	"⟦" +
	text
		.split(/(\{\{.*?\}\}|<[^>]+>)/g)
		.map((part) =>
			/^(\{\{|<)/.test(part)
				? part
				: part.replace(/[aeiouAEIOU]/g, (c) => accents[c] + accents[c]),
		)
		.join("") +
	"⟧";
mkdirSync(`${root}/catalogs/en-XA`, { recursive: true });
for (const ns of namespaces) {
	const en = JSON.parse(readFileSync(`${root}/catalogs/en/${ns}.json`, "utf8"));
	writeFileSync(
		`${root}/catalogs/en-XA/${ns}.json`,
		`${JSON.stringify(
			Object.fromEntries(
				Object.entries(en).map(([key, value]) => [key, pseudo(value)]),
			),
			null,
			2,
		)}\n`,
	);
}
const lines = [
	'import type { DesktopLocale } from "@zuse/contracts";',
	"// Generated by scripts/generate-i18n.mjs. English catalog keys are the type source.",
];
for (const ns of namespaces)
	lines.push(`import type ${ns} from "./catalogs/en/${ns}.json";`);
lines.push(
	`export type Namespace = ${namespaces.map((ns) => JSON.stringify(ns)).join(" | ")};`,
);
lines.push(
	"export type MessageKey = " +
		namespaces.map((ns) => `\`${ns}:\${keyof typeof ${ns}}\``).join(" | ") +
		";",
);
lines.push(
	"export const loaders: Readonly<Record<DesktopLocale, Readonly<Record<Namespace, () => Promise<{ default: Readonly<Record<string, string>> }>>>>> = {",
);
for (const locale of locales) {
	lines.push(` ${JSON.stringify(locale)}: {`);
	for (const ns of namespaces)
		lines.push(`  ${ns}: () => import("./catalogs/${locale}/${ns}.json"),`);
	lines.push(" },");
}
lines.push("};");
writeFileSync(`${root}/catalogs.ts`, `${lines.join("\n")}\n`);

// Keep type-independent English fallbacks adjacent to the features that use them.
mkdirSync(`${root}/english`, { recursive: true });
for (const namespace of namespaces) {
	writeFileSync(
		`${root}/english/${namespace}.ts`,
		`import { i18n } from "../index.ts";\nimport messages from "../catalogs/en/${namespace}.json";\ni18n.addResourceBundle("en", "${namespace}", messages);\n`,
	);
}
const english = Object.fromEntries(
	namespaces.map((namespace) => [
		namespace,
		JSON.parse(readFileSync(`${root}/catalogs/en/${namespace}.json`, "utf8")),
	]),
);
const { sourceRevision } = await import("./check-i18n.mjs");
const review = JSON.parse(readFileSync(`${root}/review.json`, "utf8"));
review.en.sourceRevision = sourceRevision(english);
writeFileSync(`${root}/review.json`, `${JSON.stringify(review, null, 2)}\n`);

// Regenerate translator references from the current desktop source tree.
const repository = resolve(root, "../../..");
const references = {};
function scan(directory) {
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const path = resolve(directory, entry.name);
		if (entry.isDirectory()) scan(path);
		else if (/\.tsx?$/.test(entry.name)) {
			const content = readFileSync(path, "utf8");
			for (const match of content.matchAll(
				/["'`]([a-z]+:[a-zA-Z0-9_]+)["'`]/g,
			)) {
				const key = match[1];
				references[key] ??= [];
				references[key].push({
					path: relative(repository, path),
					line: content.slice(0, match.index).split("\n").length,
				});
			}
		}
	}
}
scan(resolve(repository, "apps/renderer/src"));
scan(resolve(repository, "apps/desktop/src"));
const context = {};
for (const [namespace, messages] of Object.entries(english)) {
	for (const [key, source] of Object.entries(messages)) {
		const id = `${namespace}:${key}`;
		context[id] = {
			source,
			locations:
				references[id] ??
				references[id.replace(/_(zero|one|two|few|many|other)$/, "")] ??
				[],
			context: `${namespace} interface. Preserve named placeholders and mapped rich-text tags. See docs/localization.md for terminology.`,
		};
	}
}
writeFileSync(
	`${root}/context.json`,
	`${JSON.stringify(context, null, "\t")}\n`,
);
execFileSync(
	resolve(repository, "node_modules/.bin/biome"),
	["check", "--write", root],
	{ stdio: "inherit" },
);
