import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "../packages/i18n");
const namespaces = readdirSync(`${root}/locales/en/desktop`)
	.filter((f) => f.endsWith(".json"))
	.map((f) => f.slice(0, -5))
	.sort();
const locales = Object.keys(
	JSON.parse(readFileSync(`${root}/locales/registry.json`, "utf8")),
);
const accents = {
	a: "à",
	e: "ë",
	i: "ï",
	o: "ô",
	u: "ü",
	A: "À",
	E: "Ë",
	I: "Ï",
	O: "Ô",
	U: "Ü",
};
export const pseudo = (text) =>
	"⟦" +
	text
		.split(/(\{\{.*?\}\}|<[^>]+>)/g)
		.map((part) =>
			/^(\{\{|<)/.test(part)
				? part
				: part.replace(/[aeiouAEIOU]/g, (c) => accents[c] + accents[c]),
		)
		.join("") +
	"⟧";
mkdirSync(`${root}/locales/en-XA/desktop`, { recursive: true });
for (const ns of namespaces) {
	const en = JSON.parse(
		readFileSync(`${root}/locales/en/desktop/${ns}.json`, "utf8"),
	);
	writeFileSync(
		`${root}/locales/en-XA/desktop/${ns}.json`,
		`${JSON.stringify(
			Object.fromEntries(
				Object.entries(en).map(([key, value]) => [key, pseudo(value)]),
			),
			null,
			2,
		)}\n`,
	);
}
const lines = [
	'import type { DesktopLocale } from "@zuse/contracts";',
	"// Generated by scripts/generate-i18n.mjs. English catalog keys are the type source.",
];
for (const ns of namespaces)
	lines.push(`import type ${ns} from "../../locales/en/desktop/${ns}.json";`);
lines.push(
	`export type Namespace = ${namespaces.map((ns) => JSON.stringify(ns)).join(" | ")};`,
);
lines.push(
	"export type MessageKey = " +
		namespaces.map((ns) => `\`${ns}:\${keyof typeof ${ns}}\``).join(" | ") +
		";",
);
lines.push(
	"export const loaders: Readonly<Record<DesktopLocale, Readonly<Record<Namespace, () => Promise<{ default: Readonly<Record<string, string>> }>>>>> = {",
);
for (const locale of locales) {
	lines.push(` ${JSON.stringify(locale)}: {`);
	for (const ns of namespaces)
		lines.push(
			`  ${ns}: () => import("../../locales/${locale}/desktop/${ns}.json"),`,
		);
	lines.push(" },");
}
lines.push("};");
writeFileSync(`${root}/src/generated/desktop.ts`, `${lines.join("\n")}\n`);

// Keep type-independent English fallbacks adjacent to the features that use them.
mkdirSync(`${root}/src/generated/english`, { recursive: true });
for (const namespace of namespaces) {
	writeFileSync(
		`${root}/src/generated/english/${namespace}.ts`,
		`import { i18n } from "../../index.ts";\nimport messages from "../../../locales/en/desktop/${namespace}.json";\ni18n.addResourceBundle("en", "${namespace}", messages);\n`,
	);
}
const english = Object.fromEntries(
	namespaces.map((namespace) => [
		namespace,
		JSON.parse(
			readFileSync(`${root}/locales/en/desktop/${namespace}.json`, "utf8"),
		),
	]),
);
const { sourceRevision } = await import("./check-i18n.mjs");
const review = JSON.parse(readFileSync(`${root}/review/desktop.json`, "utf8"));
review.en.sourceRevision = sourceRevision(english);
writeFileSync(
	`${root}/review/desktop.json`,
	`${JSON.stringify(review, null, 2)}\n`,
);

// Regenerate translator references from the current desktop source tree.
const repository = resolve(root, "../..");
const references = {};
function scan(directory) {
	for (const entry of readdirSync(directory, { withFileTypes: true })) {
		const path = resolve(directory, entry.name);
		if (entry.isDirectory()) scan(path);
		else if (/\.tsx?$/.test(entry.name)) {
			const content = readFileSync(path, "utf8");
			for (const match of content.matchAll(
				/["'`]([a-z]+:[a-zA-Z0-9_]+)["'`]/g,
			)) {
				const key = match[1];
				references[key] ??= [];
				references[key].push({
					path: relative(repository, path),
					line: content.slice(0, match.index).split("\n").length,
				});
			}
		}
	}
}
scan(resolve(repository, "apps/renderer/src"));
scan(resolve(repository, "apps/desktop/src"));
const context = {};
for (const [namespace, messages] of Object.entries(english)) {
	for (const [key, source] of Object.entries(messages)) {
		const id = `${namespace}:${key}`;
		context[id] = {
			source,
			locations:
				references[id] ??
				references[id.replace(/_(zero|one|two|few|many|other)$/, "")] ??
				[],
			context: `${namespace} interface. Preserve named placeholders and mapped rich-text tags. See docs/localization.md for terminology.`,
		};
	}
}
writeFileSync(
	`${root}/context/desktop.json`,
	`${JSON.stringify(context, null, "\t")}\n`,
);
// Website resources and review history are independent from the desktop.
const websiteNamespaces = readdirSync(`${root}/locales/en/website`)
	.filter((file) => file.endsWith(".json"))
	.map((file) => file.slice(0, -5))
	.sort();
const websiteLines = [
	'import type { WebsiteLocale } from "../registry.ts";',
	"// Generated. Website resources are server-loaded; client imports must be type-only.",
];
for (const ns of websiteNamespaces)
	websiteLines.push(
		`import type ${ns} from "../../locales/en/website/${ns}.json";`,
	);
websiteLines.push(
	"export type WebsiteMessageKey = " +
		websiteNamespaces
			.map((ns) => "`" + ns + ":${keyof typeof " + ns + "}`")
			.join(" | ") +
		";",
);
websiteLines.push(
	"export type WebsiteCatalog = Readonly<Record<WebsiteMessageKey, string>>;",
);
websiteLines.push(
	"export const websiteLoaders: Record<WebsiteLocale, () => Promise<WebsiteCatalog>> = {",
);
for (const locale of locales.filter((locale) => locale !== "en-XA")) {
	websiteLines.push(`"${locale}": async () => {`);
	websiteLines.push(
		`const parts = await Promise.all([${websiteNamespaces.map((ns) => `import("../../locales/${locale}/website/${ns}.json")`).join(",")}]);`,
	);
	websiteLines.push(
		`return Object.fromEntries(parts.flatMap((part,i) => Object.entries(part.default).map(([key,value]) => [${JSON.stringify(websiteNamespaces)}[i]+":"+key,value]))) as WebsiteCatalog; },`,
	);
}
websiteLines.push("};");
writeFileSync(
	`${root}/src/generated/website.ts`,
	websiteLines.join("\n") + "\n",
);
const websiteEnglish = Object.fromEntries(
	websiteNamespaces.map((ns) => [
		ns,
		JSON.parse(readFileSync(`${root}/locales/en/website/${ns}.json`, "utf8")),
	]),
);
const websiteReview = JSON.parse(
	readFileSync(`${root}/review/website.json`, "utf8"),
);
websiteReview.en.sourceRevision = sourceRevision(websiteEnglish);
writeFileSync(
	`${root}/review/website.json`,
	JSON.stringify(websiteReview, null, "\t") + "\n",
);
const { websiteLocalizationSources } = await import(
	"./website-localization-sources.mjs"
);
const websiteContext = {};
for (const [ns, entries] of Object.entries(websiteEnglish))
	for (const [key, source] of Object.entries(entries))
		websiteContext[ns + ":" + key] = { source, locations: [] };
for (const path of websiteLocalizationSources()) {
	const content = readFileSync(resolve(repository, path), "utf8");
	for (const match of content.matchAll(/["']([a-z]+:[a-z0-9_]+)["']/g))
		if (websiteContext[match[1]])
			websiteContext[match[1]].locations.push({
				path,
				line: content.slice(0, match.index).split("\n").length,
			});
}
writeFileSync(
	`${root}/context/website.json`,
	JSON.stringify(websiteContext, null, "\t") + "\n",
);
execFileSync(
	resolve(repository, "node_modules/.bin/biome"),
	["check", "--write", root],
	{ stdio: "inherit" },
);
