import { RpcGroup } from "@effect/rpc";

import {
  AgentAvailabilityRpc,
  AgentCloseRpc,
  AgentEventsRpc,
  AgentInterruptRpc,
  AgentOpencodeInventoryRpc,
  AgentSendRpc,
  AgentSetCredentialRpc,
  AgentStartLoginRpc,
  AgentStartRpc,
  AgentUpdateProviderRpc,
} from "./agent.ts";
import { AttachmentTouchRpc, AttachmentUploadRpc } from "./attachment.ts";
import {
  AuthGetSessionRpc,
  AuthSessionChangesRpc,
  AuthSignInRpc,
  AuthSignOutRpc,
} from "./auth.ts";
import {
  BrowserCommandsRpc,
  BrowserFillForOriginRpc,
  BrowserListCredentialsRpc,
  BrowserRemoveCredentialRpc,
  BrowserRespondRpc,
  BrowserSetCredentialRpc,
} from "./browser.ts";
import {
  IndexFindReferencesRpc,
  IndexListModuleRpc,
  IndexReadChunkRpc,
  IndexReindexRpc,
  IndexSearchRpc,
  IndexStatusRpc,
  IndexStatusStreamRpc,
  IndexSymbolLookupRpc,
} from "./code-index.ts";
import { ConnectDescribeRpc } from "./connect.ts";
import {
  FsCreateDirectoryRpc,
  FsCreateFileRpc,
  FsReadExternalFileRpc,
  FsReadFileRpc,
  FsRemoveRpc,
  FsTreeRpc,
  FsWatchTreeRpc,
  FsWriteExternalFileRpc,
  FsWriteFileRpc,
} from "./fs.ts";
import {
  ExternalThreadsContinueRpc,
  ExternalThreadsListRpc,
} from "./external-thread.ts";
import { DiagnosticsExportRpc } from "./diagnostics.ts";
import {
  GitBranchesRpc,
  GitChangesRpc,
  GitCommitRpc,
  GitDiffRpc,
  GitFixFailingChecksRpc,
  GitHeadChangedRpc,
  GitInitRpc,
  GitLogRpc,
  GitDiffStatRpc,
  GitMarkReadyRpc,
  GitMergePrRpc,
  GitRevertAllRpc,
  GitRevertFileRpc,
  GitOriginRpc,
  GitPrDetailsRpc,
  GitPrStateRpc,
  GitPushRpc,
  GitRenameBranchRpc,
  GitStatusRpc,
  GitSwitchBranchRpc,
  GitUserNameRpc,
} from "./git.ts";
import {
  PermissionDecideRpc,
  PermissionListDecisionsRpc,
  PermissionListPendingRpc,
  PermissionRequestsRpc,
  PermissionRevokeDecisionRpc,
} from "./permission.ts";
import {
  PairingListTokensRpc,
  PairingRevokeTokenRpc,
  PairingStartRpc,
} from "./pairing.ts";
import { PokemonEnsureSpriteCachedRpc, PokemonPokedexRpc } from "./pokemon.ts";
import { PingRpc } from "./ping.ts";
import {
  KeybindingsGetRpc,
  KeybindingsReplaceRpc,
  KeybindingsStreamRpc,
} from "./keybindings.ts";
import {
  RepositorySettingsGetRpc,
  RepositorySettingsUpdateRpc,
} from "./repository-settings.ts";
import {
  SettingsGetRpc,
  SettingsMigrateLocalStorageRpc,
  SettingsStreamRpc,
  SettingsUpdateRpc,
} from "./settings.ts";
import { UsageReportRpc } from "./usage.ts";
import {
  PtyCloseRpc,
  PtyOpenRpc,
  PtyOutputRpc,
  PtyResizeRpc,
  PtyWriteRpc,
} from "./pty.ts";
import {
  ChatArchiveRpc,
  ChatCreateRpc,
  ChatDeleteRpc,
  ChatGetRpc,
  ChatListRpc,
  ChatMarkReadRpc,
  ChatRenameRpc,
  ChatStreamChangesRpc,
  ChatSetActiveSessionRpc,
  ChatSetWorktreeRpc,
  ChatUnarchiveRpc,
  MessagesInterruptRpc,
  MessagesListRpc,
  MessagesQueueAddRpc,
  MessagesQueueDeleteRpc,
  MessagesQueueFlushRpc,
  MessagesQueueListRpc,
  MessagesQueueReorderRpc,
  MessagesQueueResumeRpc,
  MessagesQueueSendNowRpc,
  MessagesQueueStreamRpc,
  MessagesQueueUpdateRpc,
  MessagesSendRpc,
  MessagesStreamRpc,
  SessionAnswerQuestionRpc,
  SessionArchiveRpc,
  SessionCreateRpc,
  SessionDeleteRpc,
  SessionGoalClearRpc,
  SessionGoalGetRpc,
  SessionGoalSetRpc,
  SessionGoalStreamRpc,
  SessionGetRpc,
  SessionListRpc,
  SessionRenameRpc,
  SessionResumeRpc,
  SessionSetModelRpc,
  SessionSetPermissionModeRpc,
  SessionSetProviderRpc,
  SessionSetRuntimeModeRpc,
  SessionSetWorktreeRpc,
  SessionStatusStreamRpc,
  SessionUnarchiveRpc,
} from "./session.ts";
import { SkillListRpc, SkillStreamRpc } from "./skill.ts";
import {
  WorkspaceAddRpc,
  WorkspaceCloneRepoRpc,
  WorkspaceCreateProjectRpc,
  WorkspaceGetSelectedRpc,
  WorkspaceGhAuthStatusRpc,
  WorkspaceListGithubReposRpc,
  WorkspaceListRpc,
  WorkspacePickFolderRpc,
  WorkspaceRemoveRpc,
  WorkspaceSearchFilesRpc,
  WorkspaceSetSelectedRpc,
} from "./workspace.ts";
import {
  WorktreeCreateRpc,
  WorktreeGetRpc,
  WorktreeListRpc,
  WorktreeRemoveRpc,
  WorktreeRerunSetupRpc,
  WorktreeSetupStreamRpc,
  WorktreeStartRunRpc,
} from "./worktree.ts";

/**
 * The single source of truth for every RPC method exposed by the main process.
 * Both server (apps/desktop) and client (apps/renderer) build against this.
 *
 * Add new RPCs by importing them here and including them in the group.
 */
export const MemoizeRpcs = RpcGroup.make(
  PingRpc,
  AuthGetSessionRpc,
  AuthSignInRpc,
  AuthSignOutRpc,
  AuthSessionChangesRpc,
  PairingStartRpc,
  PairingListTokensRpc,
  PairingRevokeTokenRpc,
  ConnectDescribeRpc,
  WorkspaceAddRpc,
  WorkspaceListRpc,
  WorkspaceRemoveRpc,
  WorkspacePickFolderRpc,
  WorkspaceGetSelectedRpc,
  WorkspaceSetSelectedRpc,
  WorkspaceSearchFilesRpc,
  WorkspaceCloneRepoRpc,
  WorkspaceCreateProjectRpc,
  WorkspaceListGithubReposRpc,
  WorkspaceGhAuthStatusRpc,
  ExternalThreadsListRpc,
  ExternalThreadsContinueRpc,
  PtyOpenRpc,
  PtyWriteRpc,
  PtyResizeRpc,
  PtyCloseRpc,
  PtyOutputRpc,
  GitLogRpc,
  GitStatusRpc,
  GitBranchesRpc,
  GitSwitchBranchRpc,
  GitRenameBranchRpc,
  GitUserNameRpc,
  GitHeadChangedRpc,
  GitOriginRpc,
  GitPrStateRpc,
  GitPrDetailsRpc,
  GitChangesRpc,
  GitDiffRpc,
  GitCommitRpc,
  GitPushRpc,
  GitMergePrRpc,
  GitMarkReadyRpc,
  GitInitRpc,
  GitFixFailingChecksRpc,
  GitRevertFileRpc,
  GitRevertAllRpc,
  GitDiffStatRpc,
  FsTreeRpc,
  FsWatchTreeRpc,
  FsReadFileRpc,
  FsWriteFileRpc,
  FsCreateFileRpc,
  FsCreateDirectoryRpc,
  FsRemoveRpc,
  FsReadExternalFileRpc,
  FsWriteExternalFileRpc,
  AgentAvailabilityRpc,
  AgentSetCredentialRpc,
  AgentStartRpc,
  AgentSendRpc,
  AgentInterruptRpc,
  AgentCloseRpc,
  AgentEventsRpc,
  AgentOpencodeInventoryRpc,
  AgentStartLoginRpc,
  AgentUpdateProviderRpc,
  ChatListRpc,
  ChatGetRpc,
  ChatCreateRpc,
  ChatRenameRpc,
  ChatMarkReadRpc,
  ChatStreamChangesRpc,
  ChatSetWorktreeRpc,
  ChatSetActiveSessionRpc,
  ChatArchiveRpc,
  ChatUnarchiveRpc,
  ChatDeleteRpc,
  SessionListRpc,
  SessionGetRpc,
  SessionCreateRpc,
  SessionRenameRpc,
  SessionGoalGetRpc,
  SessionGoalSetRpc,
  SessionGoalClearRpc,
  SessionGoalStreamRpc,
  SessionSetModelRpc,
  SessionSetProviderRpc,
  SessionArchiveRpc,
  SessionUnarchiveRpc,
  SessionDeleteRpc,
  SessionResumeRpc,
  SessionSetRuntimeModeRpc,
  SessionSetPermissionModeRpc,
  SessionAnswerQuestionRpc,
  SessionSetWorktreeRpc,
  SessionStatusStreamRpc,
  MessagesListRpc,
  MessagesStreamRpc,
  MessagesSendRpc,
  MessagesInterruptRpc,
  MessagesQueueListRpc,
  MessagesQueueStreamRpc,
  MessagesQueueAddRpc,
  MessagesQueueUpdateRpc,
  MessagesQueueDeleteRpc,
  MessagesQueueSendNowRpc,
  MessagesQueueReorderRpc,
  MessagesQueueFlushRpc,
  MessagesQueueResumeRpc,
  AttachmentUploadRpc,
  AttachmentTouchRpc,
  SkillListRpc,
  SkillStreamRpc,
  PermissionRequestsRpc,
  PermissionDecideRpc,
  PermissionListPendingRpc,
  PermissionListDecisionsRpc,
  PermissionRevokeDecisionRpc,
  PokemonPokedexRpc,
  PokemonEnsureSpriteCachedRpc,
  BrowserCommandsRpc,
  BrowserRespondRpc,
  BrowserSetCredentialRpc,
  BrowserListCredentialsRpc,
  BrowserRemoveCredentialRpc,
  BrowserFillForOriginRpc,
  WorktreeCreateRpc,
  WorktreeListRpc,
  WorktreeGetRpc,
  WorktreeRerunSetupRpc,
  WorktreeSetupStreamRpc,
  WorktreeStartRunRpc,
  WorktreeRemoveRpc,
  RepositorySettingsGetRpc,
  RepositorySettingsUpdateRpc,
  SettingsGetRpc,
  SettingsUpdateRpc,
  SettingsStreamRpc,
  SettingsMigrateLocalStorageRpc,
  UsageReportRpc,
  DiagnosticsExportRpc,
  KeybindingsGetRpc,
  KeybindingsReplaceRpc,
  KeybindingsStreamRpc,
  SessionSetWorktreeRpc,
  IndexStatusRpc,
  IndexStatusStreamRpc,
  IndexReindexRpc,
  IndexSearchRpc,
  IndexSymbolLookupRpc,
  IndexFindReferencesRpc,
  IndexReadChunkRpc,
  IndexListModuleRpc,
);
export type MemoizeRpcs = typeof MemoizeRpcs;

/**
 * The Electron IPC channel name used to transport RPC frames in both
 * directions. The frame body is the bytes/string emitted by the configured
 * `RpcSerialization` (we use NDJSON in v1 — see `apps/desktop/src/runtime.ts`).
 *
 * Renderer → main: `ipcRenderer.send(IPC_CHANNEL, frame)`
 * Main → renderer: `webContents.send(IPC_CHANNEL, frame)`
 */
export const IPC_CHANNEL = "zuse:rpc" as const;
