import type { DesktopLocale } from "@zuse/contracts";
// Generated by scripts/generate-i18n.mjs. English catalog keys are the type source.
import type chat from "./catalogs/en/chat.json";
import type commands from "./catalogs/en/commands.json";
import type common from "./catalogs/en/common.json";
import type connections from "./catalogs/en/connections.json";
import type desktop from "./catalogs/en/desktop.json";
import type errors from "./catalogs/en/errors.json";
import type onboarding from "./catalogs/en/onboarding.json";
import type projects from "./catalogs/en/projects.json";
import type providers from "./catalogs/en/providers.json";
import type settings from "./catalogs/en/settings.json";
import type shell from "./catalogs/en/shell.json";
import type tools from "./catalogs/en/tools.json";
import type usage from "./catalogs/en/usage.json";
export type Namespace =
	| "chat"
	| "commands"
	| "common"
	| "connections"
	| "desktop"
	| "errors"
	| "onboarding"
	| "projects"
	| "providers"
	| "settings"
	| "shell"
	| "tools"
	| "usage";
export type MessageKey =
	| `chat:${keyof typeof chat}`
	| `commands:${keyof typeof commands}`
	| `common:${keyof typeof common}`
	| `connections:${keyof typeof connections}`
	| `desktop:${keyof typeof desktop}`
	| `errors:${keyof typeof errors}`
	| `onboarding:${keyof typeof onboarding}`
	| `projects:${keyof typeof projects}`
	| `providers:${keyof typeof providers}`
	| `settings:${keyof typeof settings}`
	| `shell:${keyof typeof shell}`
	| `tools:${keyof typeof tools}`
	| `usage:${keyof typeof usage}`;
export const loaders: Readonly<
	Record<
		DesktopLocale,
		Readonly<
			Record<
				Namespace,
				() => Promise<{ default: Readonly<Record<string, string>> }>
			>
		>
	>
> = {
	en: {
		chat: () => import("./catalogs/en/chat.json"),
		commands: () => import("./catalogs/en/commands.json"),
		common: () => import("./catalogs/en/common.json"),
		connections: () => import("./catalogs/en/connections.json"),
		desktop: () => import("./catalogs/en/desktop.json"),
		errors: () => import("./catalogs/en/errors.json"),
		onboarding: () => import("./catalogs/en/onboarding.json"),
		projects: () => import("./catalogs/en/projects.json"),
		providers: () => import("./catalogs/en/providers.json"),
		settings: () => import("./catalogs/en/settings.json"),
		shell: () => import("./catalogs/en/shell.json"),
		tools: () => import("./catalogs/en/tools.json"),
		usage: () => import("./catalogs/en/usage.json"),
	},
	fr: {
		chat: () => import("./catalogs/fr/chat.json"),
		commands: () => import("./catalogs/fr/commands.json"),
		common: () => import("./catalogs/fr/common.json"),
		connections: () => import("./catalogs/fr/connections.json"),
		desktop: () => import("./catalogs/fr/desktop.json"),
		errors: () => import("./catalogs/fr/errors.json"),
		onboarding: () => import("./catalogs/fr/onboarding.json"),
		projects: () => import("./catalogs/fr/projects.json"),
		providers: () => import("./catalogs/fr/providers.json"),
		settings: () => import("./catalogs/fr/settings.json"),
		shell: () => import("./catalogs/fr/shell.json"),
		tools: () => import("./catalogs/fr/tools.json"),
		usage: () => import("./catalogs/fr/usage.json"),
	},
	de: {
		chat: () => import("./catalogs/de/chat.json"),
		commands: () => import("./catalogs/de/commands.json"),
		common: () => import("./catalogs/de/common.json"),
		connections: () => import("./catalogs/de/connections.json"),
		desktop: () => import("./catalogs/de/desktop.json"),
		errors: () => import("./catalogs/de/errors.json"),
		onboarding: () => import("./catalogs/de/onboarding.json"),
		projects: () => import("./catalogs/de/projects.json"),
		providers: () => import("./catalogs/de/providers.json"),
		settings: () => import("./catalogs/de/settings.json"),
		shell: () => import("./catalogs/de/shell.json"),
		tools: () => import("./catalogs/de/tools.json"),
		usage: () => import("./catalogs/de/usage.json"),
	},
	"zh-Hans": {
		chat: () => import("./catalogs/zh-Hans/chat.json"),
		commands: () => import("./catalogs/zh-Hans/commands.json"),
		common: () => import("./catalogs/zh-Hans/common.json"),
		connections: () => import("./catalogs/zh-Hans/connections.json"),
		desktop: () => import("./catalogs/zh-Hans/desktop.json"),
		errors: () => import("./catalogs/zh-Hans/errors.json"),
		onboarding: () => import("./catalogs/zh-Hans/onboarding.json"),
		projects: () => import("./catalogs/zh-Hans/projects.json"),
		providers: () => import("./catalogs/zh-Hans/providers.json"),
		settings: () => import("./catalogs/zh-Hans/settings.json"),
		shell: () => import("./catalogs/zh-Hans/shell.json"),
		tools: () => import("./catalogs/zh-Hans/tools.json"),
		usage: () => import("./catalogs/zh-Hans/usage.json"),
	},
	"zh-Hant": {
		chat: () => import("./catalogs/zh-Hant/chat.json"),
		commands: () => import("./catalogs/zh-Hant/commands.json"),
		common: () => import("./catalogs/zh-Hant/common.json"),
		connections: () => import("./catalogs/zh-Hant/connections.json"),
		desktop: () => import("./catalogs/zh-Hant/desktop.json"),
		errors: () => import("./catalogs/zh-Hant/errors.json"),
		onboarding: () => import("./catalogs/zh-Hant/onboarding.json"),
		projects: () => import("./catalogs/zh-Hant/projects.json"),
		providers: () => import("./catalogs/zh-Hant/providers.json"),
		settings: () => import("./catalogs/zh-Hant/settings.json"),
		shell: () => import("./catalogs/zh-Hant/shell.json"),
		tools: () => import("./catalogs/zh-Hant/tools.json"),
		usage: () => import("./catalogs/zh-Hant/usage.json"),
	},
	ja: {
		chat: () => import("./catalogs/ja/chat.json"),
		commands: () => import("./catalogs/ja/commands.json"),
		common: () => import("./catalogs/ja/common.json"),
		connections: () => import("./catalogs/ja/connections.json"),
		desktop: () => import("./catalogs/ja/desktop.json"),
		errors: () => import("./catalogs/ja/errors.json"),
		onboarding: () => import("./catalogs/ja/onboarding.json"),
		projects: () => import("./catalogs/ja/projects.json"),
		providers: () => import("./catalogs/ja/providers.json"),
		settings: () => import("./catalogs/ja/settings.json"),
		shell: () => import("./catalogs/ja/shell.json"),
		tools: () => import("./catalogs/ja/tools.json"),
		usage: () => import("./catalogs/ja/usage.json"),
	},
	ko: {
		chat: () => import("./catalogs/ko/chat.json"),
		commands: () => import("./catalogs/ko/commands.json"),
		common: () => import("./catalogs/ko/common.json"),
		connections: () => import("./catalogs/ko/connections.json"),
		desktop: () => import("./catalogs/ko/desktop.json"),
		errors: () => import("./catalogs/ko/errors.json"),
		onboarding: () => import("./catalogs/ko/onboarding.json"),
		projects: () => import("./catalogs/ko/projects.json"),
		providers: () => import("./catalogs/ko/providers.json"),
		settings: () => import("./catalogs/ko/settings.json"),
		shell: () => import("./catalogs/ko/shell.json"),
		tools: () => import("./catalogs/ko/tools.json"),
		usage: () => import("./catalogs/ko/usage.json"),
	},
	"en-XA": {
		chat: () => import("./catalogs/en-XA/chat.json"),
		commands: () => import("./catalogs/en-XA/commands.json"),
		common: () => import("./catalogs/en-XA/common.json"),
		connections: () => import("./catalogs/en-XA/connections.json"),
		desktop: () => import("./catalogs/en-XA/desktop.json"),
		errors: () => import("./catalogs/en-XA/errors.json"),
		onboarding: () => import("./catalogs/en-XA/onboarding.json"),
		projects: () => import("./catalogs/en-XA/projects.json"),
		providers: () => import("./catalogs/en-XA/providers.json"),
		settings: () => import("./catalogs/en-XA/settings.json"),
		shell: () => import("./catalogs/en-XA/shell.json"),
		tools: () => import("./catalogs/en-XA/tools.json"),
		usage: () => import("./catalogs/en-XA/usage.json"),
	},
};
